// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    words,
    prefixes,
    suffixes,
    headDistances,
    tailDistances,
    meta,
  ];
  late final Shape0 words = Shape0(
    source: i0.VersionedTable(
      entityName: 'words',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(word_hash)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 prefixes = Shape1(
    source: i0.VersionedTable(
      entityName: 'prefixes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(word_hash, prefix_hash)'],
      columns: [_column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 suffixes = Shape2(
    source: i0.VersionedTable(
      entityName: 'suffixes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(word_hash, suffix_hash)'],
      columns: [_column_4, _column_7, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 headDistances = Shape3(
    source: i0.VersionedTable(
      entityName: 'head_distances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(word_hash, distance)'],
      columns: [_column_4, _column_8, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tailDistances = Shape3(
    source: i0.VersionedTable(
      entityName: 'tail_distances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(word_hash, distance)'],
      columns: [_column_4, _column_8, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 meta = Shape4(
    source: i0.VersionedTable(
      entityName: 'meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get wordHash =>
      columnsByName['word_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get word =>
      columnsByName['word']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalOccurances =>
      columnsByName['total_occurances']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get msgOccurances =>
      columnsByName['msg_occurances']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'word_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'word',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_occurances',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'msg_occurances',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get wordHash =>
      columnsByName['word_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get prefixHash =>
      columnsByName['prefix_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get count =>
      columnsByName['count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'word_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES words (word_hash)',
      ),
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'prefix_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES words (word_hash)',
      ),
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get wordHash =>
      columnsByName['word_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get suffixHash =>
      columnsByName['suffix_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get count =>
      columnsByName['count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'suffix_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES words (word_hash)',
      ),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get wordHash =>
      columnsByName['word_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get distance =>
      columnsByName['distance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get count =>
      columnsByName['count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'distance',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get msgCount =>
      columnsByName['msg_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get wordCount =>
      columnsByName['word_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'msg_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'word_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
